#!/bin/bash

# --- AGENT INSTRUCTIONS ---
echo "---INSTRUCTIONS FOR AI AGENT---"
echo "You are looking at a structured context dump of a TypeScript project."
echo "1. Use SECTION: DIRECTORY_TREE to understand the file layout."
echo "2. Use SECTION: PUBLIC_API_SIGNATURES to understand core modules. Implementation and tests are hidden."
echo "3. Use SECTION: VITEST_LOGIC_SUMMARY and TYPESCRIPT_COVERAGE_REPORT for quality metrics."
echo "---END INSTRUCTIONS---"

# 1. Project Manifests
for file in package.json tsconfig.json eslint.config.mjs vitest.config.ts; do
  if [ -f "$file" ]; then
    echo "---FILE_START: $file---"
    cat "$file"
    echo "---FILE_END: $file---"
  fi
done

# 2. Project Structure
echo "---SECTION: DIRECTORY_TREE---"
npx tree-node-cli -L 3 -I "node_modules|dist|.git|coverage-ts|temp_api"

# 3. Architecture & Dependencies
echo "---SECTION: DEPENDENCY_GRAPH_MERMAID---"
npx depcruise lib --include-only "^lib" --output-type mermaid --no-config

# 4. Git History
echo "---SECTION: RECENT_GIT_COMMITS---"
git --no-pager log -n 10 --oneline

# 5. Public API Map (Strict Isolation)
echo "---SECTION: PUBLIC_API_SIGNATURES---"
# Create a dedicated hidden temp dir
mkdir -p .temp_agent_api
npx tsc --declaration --emitDeclarationOnly --outDir .temp_agent_api --pretty false --skipLibCheck >/dev/null 2>&1

# Find core API files, excluding tests and configs, then mask home path
find .temp_agent_api -name "*.d.ts" ! -path "*/test/*" ! -path "*/init_config/*" -exec sh -c 'echo "---API_FILE: {}---"; cat "{}"' \; | sed "s|$HOME|~|g"

# 6. Type Health
echo "---SECTION: TYPESCRIPT_COMPILER_ERRORS---"
npx tsc --noEmit --pretty false | sed "s|$HOME|~|g"

# 7. Logic & Coverage
echo "---SECTION: VITEST_LOGIC_SUMMARY---"
npx vitest run --coverage.enabled=true --coverage.reporter=text-summary --reporter=verbose --run

# 8. Type Coverage Detail
echo "---SECTION: TYPESCRIPT_COVERAGE_REPORT---"
npx typescript-coverage-report --strict

# --- CLEANUP BLOCK ---
# Removes the API temp dir and the coverage-ts folder generated by the report tool
rm -rf .temp_agent_api
rm -rf coverage-ts
# Safety check: Remove any .d.ts files accidentally emitted to root or test folders
find . -maxdepth 2 -name "*.d.ts" -delete
find ./test -name "*.d.ts" -delete 2>/dev/null

echo "---CLEANUP_COMPLETE---"
